sudo: required
services:
    - docker

before_install:
    - docker build -t ananda-raj/study-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ananda-raj/study-docker-react npm run test -- --coverage
